// Empty State Illustrations - Generated by Gemini 3 Pro

export const IllustrationConnect = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 120 120"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    {/* Left Card */}
    <rect
      x="15"
      y="35"
      width="40"
      height="50"
      rx="6"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M25 50H45"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeOpacity="0.5"
    />
    <path
      d="M25 65H35"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeOpacity="0.5"
    />

    {/* Right Card */}
    <rect
      x="65"
      y="35"
      width="40"
      height="50"
      rx="6"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M75 50H95"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeOpacity="0.5"
    />
    <path
      d="M85 65H95"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeOpacity="0.5"
    />

    {/* Accent Connector */}
    <circle cx="60" cy="60" r="12" fill="white" stroke="#6366f1" strokeWidth="2" />
    <path
      d="M54 60H66M60 54V66"
      stroke="#6366f1"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

export const IllustrationSearch = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 120 120"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    {/* Abstract UI Background */}
    <rect
      x="20"
      y="25"
      width="80"
      height="70"
      rx="8"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeDasharray="4 4"
      strokeOpacity="0.5"
    />

    {/* Magnifying Glass */}
    <circle
      cx="55"
      cy="55"
      r="20"
      stroke="#94a3b8"
      strokeWidth="2"
      fill="white"
    />
    <path
      d="M70 70L85 85"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />

    {/* Accent Sparkles */}
    <path
      d="M55 45V49M55 61V65M45 55H49M61 55H65"
      stroke="#6366f1"
      strokeWidth="2"
      strokeLinecap="round"
    />
    <path
      d="M85 35L88 41L94 44L88 47L85 53L82 47L76 44L82 41L85 35Z"
      fill="#6366f1"
      stroke="#6366f1"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

export const IllustrationNoResults = (props: React.SVGProps<SVGSVGElement>) => (
  <svg
    viewBox="0 0 120 120"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    {/* Ghost File */}
    <path
      d="M35 25H70L85 40V95H35V25Z"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeDasharray="6 6"
    />
    
    {/* Folded Corner */}
    <path
      d="M70 25V40H85"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeOpacity="0.5"
    />

    {/* Empty State Lines */}
    <path
      d="M50 55H70"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeOpacity="0.3"
    />
    <path
      d="M50 70H60"
      stroke="#94a3b8"
      strokeWidth="2"
      strokeLinecap="round"
      strokeOpacity="0.3"
    />

    {/* Accent Question Mark Bubble */}
    <circle cx="85" cy="85" r="14" fill="white" stroke="#6366f1" strokeWidth="2" />
    <path
      d="M85 78C87.5 78 89 79.5 89 81.5C89 83.5 87 84 86.5 85.5C86 87 85 87 85 88"
      stroke="#6366f1"
      strokeWidth="2"
      strokeLinecap="round"
    />
    <circle cx="85" cy="92" r="1" fill="#6366f1" />
  </svg>
);
